<?php

 return [
    ['icon'=>'nav-icon fas fa-th',
    'title'=>'Dashboard',
    'route'=>'dashboard.dashboard.index',
    'active'=>'dashboard.dashboard*',
    ],
    ['icon'=>'nav-icon fas fa-th',
    'title'=>'Categories',
    'route'=>'dashboard.categories.index',
    'active'=>'dashboard.categories.*',
    'ability'=>'categories.view',
    
    ],
    ['icon'=>'nav-icon fas fa-th',
    'title'=>'Products',
    'route'=>'dashboard.products.index',
    'active'=>'dashboard.products.*',
    'ability'=>'products.view',
    ],
    ['icon'=>'nav-icon fas fa-th',
    'title'=>'Stores',
    'route'=>'dashboard.stores.index',
    'active'=>'dashboard.stores.*',
    'ability'=>'stores.view',
    ],
    ['icon'=>'nav-icon fas fa-th',
    'title'=>'Orders',
    'route'=>'dashboard.orders.index',
    'active'=>'dashboard.orders.*',
    'ability'=>'orders.view',
    'badge'=>'New'
    ],
    ['icon'=>'nav-icon fas fa-th',
    'title'=>'Roles',
    'route'=>'dashboard.roles.index',
    'active'=>'dashboard.roles.*',
    'ability'=>'roles.view',
    'badge'=>'New'
    ],
    ['icon'=>'nav-icon fas fa-th',
    'title'=>'Admins',
    'route'=>'dashboard.admins.index',
    'active'=>'dashboard.admins.*',
    'ability'=>'admins.view',
    'badge'=>'New'
    ],
    ['icon'=>'nav-icon fas fa-th',
    'title'=>'Users',
    'route'=>'dashboard.users.index',
    'active'=>'dashboard.users.*',
    'ability'=>'users.view',
    'badge'=>'New'
    ],
 ];